version: "3.8"

services:
  db:
    image: francescopinto02/pokedex-db:latest
    container_name: pokedex_db
    restart: always
    environment:
      POSTGRES_USER: pokedex_user
      POSTGRES_PASSWORD: pokedex_pass
      POSTGRES_DB: pokedex_db
    ports:
      - "5432:5432"
    volumes:
      - pokedex_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokedex_user -d pokedex_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: francescopinto02/pokedex-backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pokedex_db
      SPRING_DATASOURCE_USERNAME: pokedex_user
      SPRING_DATASOURCE_PASSWORD: pokedex_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      JWT_SECRET: supersegretissimo123
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: francescopinto02/pokedex-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pokedex_data:


